version: "3"
services:
  mongo:
    image: "mongo:6.0.5"
    environment:
      MONGO_INITDB_DATABASE: todo_list
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker-cache/mongodb:/data/db
